title:            "三叶"
description:      ""
url:              "https://chaoandlong.github.io"
signoff:          "三叶"
facebook_appid:   
google_analytics: 
timezone:         Asia/Beijing
highlighter:      pygments
future:           true

links:
  - name:         Blog
    url:          /
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about.html

permalink:        /:title.html
markdown:         kramdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
sass:
  style: compressed
